calibration:
  board_center:
  - 400.0
  - 400.0
  board_radius_px: 400.0
  homography_matrix:
  - - 1.9016215484520118
    - 0.09108064699230872
    - -734.1119896696679
  - - -0.007367713637281963
    - 2.28328350179887
    - -289.85770585874286
  - - 0.000299994393501885
    - 0.00020833614149108428
    - 1.0
  method: manual
  mm_per_pixel: 0.425
  timestamp: 1766430828.185503
